# Header
menu:
  首页: /
  文章列表: /archives
  关于: /about
rss: /atom.xml
sitemap: /sitemap.xml    

# Content
excerpt_link: 继续阅读
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- recent_posts
- tagcloud
- category
- archive
- tag  
- links
- recent_comments  

# Links
links:
  主题作者: http://xiguabaobao.com
  热前端: http://reqianduan.com

# Miscellaneous
google_analytics: true
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: daemonghost

# Baidu share
baidushare: true

switch_banner: true
banner_count: 6

tinysou: true
